### PR TITLE
Fix sequencing challenge

### LINKED ISSUE #201: Fix sequencing challenge
It's been really bugging me when there are multiple of the same departure gates in a row, so this will add a cap to the amount of same-gate departures

### PR DESCRIPTION
**Pull request by checkandmate1**
Fixed the sequencing challenge by adding a cap to the amount of same-gate departures.

Fixes #201

### CODE REVIEW

File: world.go [hunk 1]
```diff
@@ -916,6 +940,20 @@ func (w *World) CreateDeparture(departureAirport, runway, category string, chall
...
 	}
+	for {
+		if lastDeparture != nil && dep.Exit == lastDeparture.Exit && w.sameGateDepartures >= w.sameDepartureCap {
+			_, dep, _ = getExit()
+		} else {
+			break
+		}
+	}
+
+	if w.sameGateDepartures == w.sameDepartureCap+4 || (lastDeparture != nil && dep.Exit != lastDeparture.Exit) { // reset back to zero if its at 7 or if there is a new gate
```
Comment (mmp) [inline world.go:951]: I'm a little unclear on why the `+4` here? More generally, the `3` and `4` constant should probably be named, e.g. `const maxSameGateDepartures = 3`, etc, just to make the intent clear.

File: world.go [hunk 2]
```diff
@@ -917,6 +924,20 @@ func (w *World) CreateDeparture(departureAirport, runway, category string, chall
 		dep = &ap.Departures[idx]
 	}
 
+	if lastDeparture == nil || (dep.Exit == lastDeparture.Exit && w.sameGateDepartures >= w.sameDepartureCap) {
```
Comment (mmp) [inline world.go:927]: Is the `lastDeparture == nil` test correct? (Should this be `if lastDeparture != nil && dep.Exit == ...`?) Currently doesn't this mean we never spawn a departure since `lastDeparture` is `nil` the first time this is called and so it will never return a valid departure?

File: world.go [hunk 3]
```diff
@@ -924,7 +924,7 @@ func (w *World) CreateDeparture(departureAirport, runway, category string, chall
 		dep = &ap.Departures[idx]
 	}
 
-	if lastDeparture == nil || (dep.Exit == lastDeparture.Exit && w.sameGateDepartures >= w.sameDepartureCap) {
+	if lastDeparture != nil || (dep.Exit == lastDeparture.Exit && w.sameGateDepartures >= w.sameDepartureCap) {
```
Comment (mmp) [inline world.go:927]: Shouldn't the `||` be an `&&`?
